version:  '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/mysql_data:/var/lib/mysql'

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "${ADMINER_PORT}:8080"


  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
     - './:/usr/src/app'
    #user: ${LOCAL_USER}